name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    uses: ./.github/workflows/ci-steps.yml
    with:
      task: checkstyleMain checkstyleTest

  test:
    uses: ./.github/workflows/ci-steps.yml
    needs: checkstyle
    with:
      task: test

  coverage:
    uses: ./.github/workflows/ci-steps.yml
    needs: test
    with:
      task: jacocoTestReport jacocoTestCoverageVerification

  build:
    uses: ./.github/workflows/ci-steps.yml
    needs: coverage
    with:
      task: build
